"""
Django settings for SGP project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fsgnwq531w1i!qyh^g^sf3ik^xm*jjb(@*rv4mx=in@yiu-9=+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
"""
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',

]
"""

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #mis apps
    'login',
    'main',
    'administracion',
    'proyectos',
    'analitica_universitaria',

]


AUTHENTICATION_BACKENDS = [
    'login.backends.CustomBackend',  # Asegúrate de que la ruta sea correcta
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    #se desactivo porque el inicio de sesion es traves de api 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SGP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        #'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SGP.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "db_sgp",
        "USER": "postgres",
        "PASSWORD": "2903",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',
    }
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }
}
"""

# settings.py
""" cuando termine de modificar usar esta
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',
    }
}
"""
# settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Usar PostgreSQL
        'NAME': 'db_analitica_universitaria',  # Nombre de tu base de datos
        'USER': 'postgres',  # Usuario de la base de datos
        'PASSWORD': '2903',  # Contraseña del usuario
        'HOST': 'localhost',  # Dirección del servidor de la base de datos (localhost si está en la misma máquina)
        'PORT': '5432',  # Puerto por defecto para PostgreSQL
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# settings.py


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



###############################PROPIAS
# api
#API_URL = "http://190.217.58.246:5187/api/SGP/"  
API_URL = "http://190.217.58.246:5187/api/SGD/procedures/execute"

#API_URL = "http://127.0.0.1:5187/api/SGD/procedures/execute"

#expiren cuando se cierre el navegador, 
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

#se guarde temporalmente en la memoria del servidor, Esto almacena la sesión en una cookie segura en el navegador del usuario.
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'


# La ruta a la que se redirige a los usuarios no autenticados
#LOGIN_URL = '/login/' 