# Generated by Django 5.1 on 2024-08-10 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=25)),
                ('documento', models.CharField(max_length=25)),
                ('avatar', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=255)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.persona')),
            ],
        ),
    ]
